// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Recipe struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedBy   string
	Name        string
	Ingredients string
	Steps       string
	Notes       sql.NullString
}

type User struct {
	ID             int64
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}

type UserRecipe struct {
	UserID    int64
	RecipeID  int64
	Data      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
