// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_recipes.sql

package database

import (
	"context"
)

const createUserRecipe = `-- name: CreateUserRecipe :exec
INSERT INTO user_recipes(user_id, recipe_id, data) VALUES(?, ?, ?)
`

type CreateUserRecipeParams struct {
	UserID   int64
	RecipeID int64
	Data     string
}

func (q *Queries) CreateUserRecipe(ctx context.Context, arg CreateUserRecipeParams) error {
	_, err := q.db.ExecContext(ctx, createUserRecipe, arg.UserID, arg.RecipeID, arg.Data)
	return err
}
