package cookbook

func MakeMockCookbook() Cookbook {
	return Cookbook{
		Recipes: []Recipe{
			// Breakfast
			NewRecipe(
				"classic pancakes",
				[]Ingredient{
					NewIngredient("flour", 2, "cups"),
					NewIngredient("milk", 1, "cups"),
					NewIngredient("egg", 1, "whole"),
					NewIngredient("sugar", 2, "tbsp"),
					NewIngredient("baking powder", 4, "tsp"),
					NewIngredient("butter", 3, "tbsp"),
				},
				[]string{
					"mix dry ingredients",
					"whisk together wet ingredients",
					"combine wet and dry",
					"cook on griddle until bubbles form",
					"flip and cook other side",
				},
				"dont overmix the batter",
			),
			NewRecipe(
				"french toast",
				[]Ingredient{
					NewIngredient("bread", 8, "slices"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("milk", 1, "cups"),
					NewIngredient("cinnamon", 1, "tsp"),
					NewIngredient("vanilla", 1, "tsp"),
				},
				[]string{
					"whisk eggs, milk, cinnamon, vanilla",
					"dip bread in mixture",
					"cook in buttered pan until golden",
				},
				"use day-old bread",
			),
			NewRecipe(
				"scrambled eggs",
				[]Ingredient{
					NewIngredient("egg", 6, "whole"),
					NewIngredient("butter", 2, "tbsp"),
					NewIngredient("milk", 2, "tbsp"),
					NewIngredient("salt", 1, "tsp"),
				},
				[]string{
					"whisk eggs with milk and salt",
					"melt butter in pan",
					"pour in eggs and stir gently",
					"cook until just set",
				},
				"low heat makes them creamy",
			),
			NewRecipe(
				"waffles",
				[]Ingredient{
					NewIngredient("flour", 2, "cups"),
					NewIngredient("milk", 2, "cups"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("sugar", 2, "tbsp"),
					NewIngredient("baking powder", 4, "tsp"),
					NewIngredient("vanilla", 1, "tsp"),
				},
				[]string{
					"mix dry ingredients",
					"beat wet ingredients separately",
					"combine and let rest 5 minutes",
					"pour into waffle iron",
					"cook until golden and crisp",
				},
				"dont open waffle iron too early",
			),
			NewRecipe(
				"oatmeal",
				[]Ingredient{
					NewIngredient("oats", 1, "cup"),
					NewIngredient("water", 2, "cups"),
					NewIngredient("salt", 1, "tsp"),
					NewIngredient("brown sugar", 2, "tbsp"),
				},
				[]string{
					"bring water and salt to boil",
					"add oats and reduce heat",
					"simmer for 5 minutes",
					"stir in sugar",
				},
				"add fruit or nuts for variety",
			),
			NewRecipe(
				"breakfast burrito",
				[]Ingredient{
					NewIngredient("egg", 4, "whole"),
					NewIngredient("tortilla", 4, "whole"),
					NewIngredient("cheese", 1, "cup"),
					NewIngredient("bacon", 6, "strips"),
					NewIngredient("salsa", 1, "cup"),
				},
				[]string{
					"cook bacon until crispy",
					"scramble eggs",
					"warm tortillas",
					"fill with eggs, bacon, cheese",
					"top with salsa and roll",
				},
				"add hot sauce if desired",
			),
			NewRecipe(
				"eggs benedict",
				[]Ingredient{
					NewIngredient("egg", 4, "whole"),
					NewIngredient("english muffin", 2, "whole"),
					NewIngredient("ham", 4, "slices"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("lemon juice", 1, "tbsp"),
				},
				[]string{
					"poach eggs",
					"toast english muffins",
					"heat ham",
					"make hollandaise sauce",
					"assemble and serve",
				},
				"keep hollandaise warm but not hot",
			),
			NewRecipe(
				"breakfast sandwich",
				[]Ingredient{
					NewIngredient("egg", 2, "whole"),
					NewIngredient("english muffin", 2, "whole"),
					NewIngredient("cheese", 2, "slices"),
					NewIngredient("bacon", 4, "strips"),
				},
				[]string{
					"cook bacon",
					"fry eggs",
					"toast muffins",
					"layer egg, cheese, bacon",
					"serve hot",
				},
				"can substitute sausage for bacon",
			),
			NewRecipe(
				"bagel with cream cheese",
				[]Ingredient{
					NewIngredient("bagel", 2, "whole"),
					NewIngredient("cream cheese", 4, "tbsp"),
					NewIngredient("smoked salmon", 4, "oz"),
					NewIngredient("red onion", 1, "whole"),
					NewIngredient("capers", 2, "tbsp"),
				},
				[]string{
					"slice and toast bagels",
					"spread cream cheese",
					"top with salmon, onion, capers",
				},
				"use everything bagels for best flavor",
			),
			NewRecipe(
				"smoothie bowl",
				[]Ingredient{
					NewIngredient("banana", 2, "whole"),
					NewIngredient("berries", 1, "cup"),
					NewIngredient("yogurt", 1, "cup"),
					NewIngredient("honey", 2, "tbsp"),
					NewIngredient("granola", 1, "cup"),
				},
				[]string{
					"blend banana, berries, yogurt",
					"pour into bowl",
					"top with granola and honey",
				},
				"freeze banana for thicker consistency",
			),
			// Lunch
			NewRecipe(
				"grilled cheese",
				[]Ingredient{
					NewIngredient("bread", 2, "slices"),
					NewIngredient("cheese", 2, "slices"),
					NewIngredient("butter", 2, "tbsp"),
				},
				[]string{
					"butter one side of each bread slice",
					"place cheese between bread",
					"grill in pan over medium heat",
					"flip when golden brown",
				},
				"use low heat to prevent burning",
			),
			NewRecipe(
				"BLT sandwich",
				[]Ingredient{
					NewIngredient("bread", 2, "slices"),
					NewIngredient("bacon", 4, "strips"),
					NewIngredient("lettuce", 2, "leaves"),
					NewIngredient("tomato", 1, "whole"),
					NewIngredient("mayo", 2, "tbsp"),
				},
				[]string{
					"cook bacon until crispy",
					"toast bread",
					"spread mayo on bread",
					"layer bacon, lettuce, tomato",
				},
				"slice tomato thick for best texture",
			),
			NewRecipe(
				"chicken caesar wrap",
				[]Ingredient{
					NewIngredient("chicken breast", 1, "lb"),
					NewIngredient("tortilla", 4, "whole"),
					NewIngredient("romaine lettuce", 2, "cups"),
					NewIngredient("parmesan", 1, "cup"),
					NewIngredient("caesar dressing", 1, "cup"),
				},
				[]string{
					"grill and slice chicken",
					"toss lettuce with dressing",
					"warm tortillas",
					"fill with chicken, lettuce, parmesan",
					"roll up tightly",
				},
				"chill before serving",
			),
			NewRecipe(
				"tuna salad",
				[]Ingredient{
					NewIngredient("tuna", 2, "cans"),
					NewIngredient("mayo", 4, "tbsp"),
					NewIngredient("celery", 2, "stalks"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("lemon juice", 1, "tbsp"),
				},
				[]string{
					"drain tuna",
					"chop celery and onion",
					"mix all ingredients",
					"season with salt and pepper",
				},
				"serve on bread or with crackers",
			),
			NewRecipe(
				"quesadilla",
				[]Ingredient{
					NewIngredient("tortilla", 2, "whole"),
					NewIngredient("cheese", 2, "cups"),
					NewIngredient("chicken", 1, "cup"),
					NewIngredient("bell pepper", 1, "whole"),
					NewIngredient("onion", 1, "whole"),
				},
				[]string{
					"saute vegetables",
					"place cheese on tortilla",
					"add chicken and vegetables",
					"fold and grill until crispy",
				},
				"serve with sour cream and salsa",
			),
			NewRecipe(
				"club sandwich",
				[]Ingredient{
					NewIngredient("bread", 3, "slices"),
					NewIngredient("turkey", 4, "slices"),
					NewIngredient("bacon", 4, "strips"),
					NewIngredient("lettuce", 2, "leaves"),
					NewIngredient("tomato", 1, "whole"),
					NewIngredient("mayo", 3, "tbsp"),
				},
				[]string{
					"toast bread",
					"cook bacon",
					"spread mayo on all bread",
					"layer turkey, bacon, lettuce, tomato",
					"cut into quarters",
				},
				"secure with toothpicks",
			),
			NewRecipe(
				"chicken noodle soup",
				[]Ingredient{
					NewIngredient("chicken breast", 1, "lb"),
					NewIngredient("chicken broth", 6, "cups"),
					NewIngredient("carrot", 2, "whole"),
					NewIngredient("celery", 2, "stalks"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("noodles", 2, "cups"),
				},
				[]string{
					"dice vegetables",
					"cook chicken in broth",
					"remove and shred chicken",
					"saute vegetables",
					"add broth and chicken back",
					"add noodles and simmer",
				},
				"season with herbs",
			),
			NewRecipe(
				"tomato soup",
				[]Ingredient{
					NewIngredient("tomato", 8, "whole"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("vegetable broth", 4, "cups"),
					NewIngredient("heavy cream", 1, "cup"),
				},
				[]string{
					"roast tomatoes and garlic",
					"saute onion",
					"blend with broth",
					"simmer for 20 minutes",
					"stir in cream",
				},
				"serve with grilled cheese",
			),
			NewRecipe(
				"minestrone soup",
				[]Ingredient{
					NewIngredient("vegetable broth", 6, "cups"),
					NewIngredient("tomato", 4, "whole"),
					NewIngredient("kidney beans", 1, "can"),
					NewIngredient("pasta", 1, "cup"),
					NewIngredient("carrot", 2, "whole"),
					NewIngredient("celery", 2, "stalks"),
					NewIngredient("zucchini", 1, "whole"),
				},
				[]string{
					"dice all vegetables",
					"saute vegetables",
					"add broth and tomatoes",
					"simmer 20 minutes",
					"add pasta and beans",
					"cook until pasta tender",
				},
				"top with parmesan",
			),
			NewRecipe(
				"french onion soup",
				[]Ingredient{
					NewIngredient("onion", 6, "whole"),
					NewIngredient("beef broth", 6, "cups"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("bread", 4, "slices"),
					NewIngredient("gruyere cheese", 2, "cups"),
				},
				[]string{
					"slice onions thin",
					"caramelize in butter for 40 minutes",
					"add broth and simmer",
					"ladle into bowls",
					"top with bread and cheese",
					"broil until cheese melts",
				},
				"patience is key for caramelizing",
			),
			// Dinner - Pasta
			NewRecipe(
				"spaghetti carbonara",
				[]Ingredient{
					NewIngredient("spaghetti", 1, "lb"),
					NewIngredient("bacon", 8, "strips"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("parmesan", 1, "cup"),
					NewIngredient("black pepper", 1, "tsp"),
				},
				[]string{
					"cook spaghetti",
					"fry bacon until crispy",
					"whisk eggs and parmesan",
					"toss hot pasta with egg mixture",
					"add bacon",
				},
				"work quickly so eggs dont scramble",
			),
			NewRecipe(
				"fettuccine alfredo",
				[]Ingredient{
					NewIngredient("fettuccine", 1, "lb"),
					NewIngredient("butter", 8, "tbsp"),
					NewIngredient("heavy cream", 2, "cups"),
					NewIngredient("parmesan", 2, "cups"),
					NewIngredient("garlic", 3, "cloves"),
				},
				[]string{
					"cook fettuccine",
					"melt butter with garlic",
					"add cream and simmer",
					"stir in parmesan",
					"toss with pasta",
				},
				"save pasta water to thin sauce",
			),
			NewRecipe(
				"lasagna",
				[]Ingredient{
					NewIngredient("lasagna noodles", 12, "sheets"),
					NewIngredient("ground beef", 2, "lbs"),
					NewIngredient("ricotta cheese", 2, "cups"),
					NewIngredient("mozzarella", 3, "cups"),
					NewIngredient("tomato sauce", 4, "cups"),
					NewIngredient("parmesan", 1, "cup"),
				},
				[]string{
					"brown ground beef",
					"mix ricotta with egg",
					"layer noodles, meat, cheese, sauce",
					"repeat layers",
					"top with mozzarella",
					"bake at 375F for 45 minutes",
				},
				"let rest 15 minutes before cutting",
			),
			NewRecipe(
				"penne arrabbiata",
				[]Ingredient{
					NewIngredient("penne", 1, "lb"),
					NewIngredient("tomato", 6, "whole"),
					NewIngredient("garlic", 6, "cloves"),
					NewIngredient("red pepper flakes", 2, "tsp"),
					NewIngredient("olive oil", 4, "tbsp"),
				},
				[]string{
					"cook penne",
					"saute garlic in olive oil",
					"add crushed tomatoes and red pepper",
					"simmer 20 minutes",
					"toss with pasta",
				},
				"adjust spice level to taste",
			),
			NewRecipe(
				"mac and cheese",
				[]Ingredient{
					NewIngredient("macaroni", 1, "lb"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("flour", 4, "tbsp"),
					NewIngredient("milk", 3, "cups"),
					NewIngredient("cheddar cheese", 3, "cups"),
				},
				[]string{
					"cook macaroni",
					"make roux with butter and flour",
					"add milk and stir until thick",
					"melt in cheese",
					"combine with pasta",
				},
				"bake with breadcrumb topping optional",
			),
			NewRecipe(
				"spaghetti bolognese",
				[]Ingredient{
					NewIngredient("spaghetti", 1, "lb"),
					NewIngredient("ground beef", 1, "lb"),
					NewIngredient("tomato sauce", 3, "cups"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("carrot", 2, "whole"),
					NewIngredient("celery", 2, "stalks"),
					NewIngredient("red wine", 1, "cup"),
				},
				[]string{
					"dice vegetables",
					"brown beef",
					"add vegetables and cook",
					"add wine and reduce",
					"add tomato sauce and simmer 1 hour",
					"serve over spaghetti",
				},
				"longer simmering improves flavor",
			),
			NewRecipe(
				"pesto pasta",
				[]Ingredient{
					NewIngredient("pasta", 1, "lb"),
					NewIngredient("basil", 3, "cups"),
					NewIngredient("pine nuts", 1, "cup"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("parmesan", 1, "cup"),
					NewIngredient("olive oil", 1, "cup"),
				},
				[]string{
					"cook pasta",
					"blend basil, pine nuts, garlic",
					"add parmesan and olive oil",
					"blend until smooth",
					"toss with hot pasta",
				},
				"add pasta water to thin if needed",
			),
			NewRecipe(
				"baked ziti",
				[]Ingredient{
					NewIngredient("ziti", 1, "lb"),
					NewIngredient("ricotta cheese", 2, "cups"),
					NewIngredient("mozzarella", 3, "cups"),
					NewIngredient("tomato sauce", 4, "cups"),
					NewIngredient("ground beef", 1, "lb"),
				},
				[]string{
					"cook ziti",
					"brown ground beef",
					"mix pasta with ricotta and sauce",
					"transfer to baking dish",
					"top with mozzarella",
					"bake at 375F for 30 minutes",
				},
				"cover with foil first 20 minutes",
			),
			// Dinner - Chicken
			NewRecipe(
				"roast chicken",
				[]Ingredient{
					NewIngredient("whole chicken", 1, "whole"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("lemon", 2, "whole"),
					NewIngredient("garlic", 8, "cloves"),
					NewIngredient("rosemary", 3, "sprigs"),
				},
				[]string{
					"pat chicken dry",
					"rub with butter and seasonings",
					"stuff with lemon and garlic",
					"roast at 425F for 1 hour",
					"let rest before carving",
				},
				"check internal temp reaches 165F",
			),
			NewRecipe(
				"chicken parmesan",
				[]Ingredient{
					NewIngredient("chicken breast", 4, "whole"),
					NewIngredient("breadcrumbs", 2, "cups"),
					NewIngredient("parmesan", 1, "cup"),
					NewIngredient("mozzarella", 2, "cups"),
					NewIngredient("tomato sauce", 2, "cups"),
					NewIngredient("egg", 2, "whole"),
				},
				[]string{
					"pound chicken thin",
					"dip in egg then breadcrumbs",
					"fry until golden",
					"top with sauce and cheese",
					"bake at 375F until cheese melts",
				},
				"serve over pasta",
			),
			NewRecipe(
				"chicken stir fry",
				[]Ingredient{
					NewIngredient("chicken breast", 1, "lb"),
					NewIngredient("soy sauce", 4, "tbsp"),
					NewIngredient("broccoli", 2, "cups"),
					NewIngredient("bell pepper", 2, "whole"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("ginger", 2, "tbsp"),
				},
				[]string{
					"cut chicken into pieces",
					"stir fry chicken in hot wok",
					"remove chicken",
					"stir fry vegetables",
					"add chicken back with sauce",
				},
				"serve over rice",
			),
			NewRecipe(
				"chicken fajitas",
				[]Ingredient{
					NewIngredient("chicken breast", 2, "lbs"),
					NewIngredient("bell pepper", 3, "whole"),
					NewIngredient("onion", 2, "whole"),
					NewIngredient("fajita seasoning", 3, "tbsp"),
					NewIngredient("tortillas", 12, "whole"),
				},
				[]string{
					"slice chicken and vegetables",
					"cook chicken with seasoning",
					"add vegetables and cook",
					"warm tortillas",
					"serve with toppings",
				},
				"add lime juice before serving",
			),
			NewRecipe(
				"buffalo wings",
				[]Ingredient{
					NewIngredient("chicken wings", 3, "lbs"),
					NewIngredient("hot sauce", 1, "cup"),
					NewIngredient("butter", 8, "tbsp"),
					NewIngredient("garlic powder", 1, "tsp"),
				},
				[]string{
					"bake wings at 400F for 45 minutes",
					"melt butter with hot sauce",
					"toss wings in sauce",
				},
				"serve with ranch or blue cheese",
			),
			NewRecipe(
				"chicken teriyaki",
				[]Ingredient{
					NewIngredient("chicken thigh", 2, "lbs"),
					NewIngredient("soy sauce", 1, "cup"),
					NewIngredient("brown sugar", 4, "tbsp"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("ginger", 2, "tbsp"),
				},
				[]string{
					"mix soy sauce, sugar, garlic, ginger",
					"marinate chicken 30 minutes",
					"grill or pan fry chicken",
					"brush with extra sauce",
				},
				"serve over rice with vegetables",
			),
			NewRecipe(
				"lemon chicken",
				[]Ingredient{
					NewIngredient("chicken breast", 4, "whole"),
					NewIngredient("lemon", 3, "whole"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("chicken broth", 1, "cup"),
				},
				[]string{
					"season and cook chicken",
					"make sauce with lemon, butter, garlic",
					"simmer chicken in sauce",
				},
				"garnish with lemon slices",
			),
			NewRecipe(
				"honey garlic chicken",
				[]Ingredient{
					NewIngredient("chicken thigh", 2, "lbs"),
					NewIngredient("honey", 1, "cup"),
					NewIngredient("soy sauce", 4, "tbsp"),
					NewIngredient("garlic", 6, "cloves"),
					NewIngredient("ginger", 1, "tbsp"),
				},
				[]string{
					"mix honey, soy sauce, garlic, ginger",
					"cook chicken until done",
					"add sauce and simmer until thick",
				},
				"garnish with sesame seeds",
			),
			// Dinner - Beef
			NewRecipe(
				"beef tacos",
				[]Ingredient{
					NewIngredient("ground beef", 2, "lbs"),
					NewIngredient("taco seasoning", 4, "tbsp"),
					NewIngredient("taco shells", 12, "whole"),
					NewIngredient("lettuce", 2, "cups"),
					NewIngredient("tomato", 3, "whole"),
					NewIngredient("cheese", 2, "cups"),
				},
				[]string{
					"brown ground beef",
					"add seasoning and water",
					"simmer until thickened",
					"fill shells with meat and toppings",
				},
				"warm shells before filling",
			),
			NewRecipe(
				"meatballs",
				[]Ingredient{
					NewIngredient("ground beef", 2, "lbs"),
					NewIngredient("breadcrumbs", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("parmesan", 1, "cup"),
				},
				[]string{
					"mix all ingredients",
					"form into balls",
					"bake at 400F for 20 minutes",
				},
				"dont overmix or they get tough",
			),
			NewRecipe(
				"beef stew",
				[]Ingredient{
					NewIngredient("beef chuck", 2, "lbs"),
					NewIngredient("potato", 4, "whole"),
					NewIngredient("carrot", 4, "whole"),
					NewIngredient("onion", 2, "whole"),
					NewIngredient("beef broth", 6, "cups"),
					NewIngredient("tomato paste", 3, "tbsp"),
				},
				[]string{
					"brown beef in chunks",
					"add vegetables and broth",
					"add tomato paste and seasonings",
					"simmer 2 hours until tender",
				},
				"great in slow cooker",
			),
			NewRecipe(
				"meatloaf",
				[]Ingredient{
					NewIngredient("ground beef", 2, "lbs"),
					NewIngredient("breadcrumbs", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("ketchup", 1, "cup"),
				},
				[]string{
					"mix beef, breadcrumbs, eggs, onion",
					"form into loaf",
					"top with ketchup",
					"bake at 350F for 1 hour",
				},
				"let rest 10 minutes before slicing",
			),
			NewRecipe(
				"beef stroganoff",
				[]Ingredient{
					NewIngredient("beef sirloin", 2, "lbs"),
					NewIngredient("mushrooms", 3, "cups"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("sour cream", 1, "cup"),
					NewIngredient("beef broth", 2, "cups"),
				},
				[]string{
					"slice beef thin",
					"brown beef and set aside",
					"saute mushrooms and onions",
					"add broth and simmer",
					"stir in sour cream and beef",
				},
				"serve over egg noodles",
			),
			NewRecipe(
				"chili",
				[]Ingredient{
					NewIngredient("ground beef", 2, "lbs"),
					NewIngredient("kidney beans", 2, "cans"),
					NewIngredient("tomato", 6, "whole"),
					NewIngredient("onion", 2, "whole"),
					NewIngredient("chili powder", 4, "tbsp"),
					NewIngredient("cumin", 2, "tsp"),
				},
				[]string{
					"brown beef with onions",
					"add tomatoes and spices",
					"add beans",
					"simmer 1 hour",
				},
				"top with cheese and sour cream",
			),
			NewRecipe(
				"pot roast",
				[]Ingredient{
					NewIngredient("beef roast", 3, "lbs"),
					NewIngredient("potato", 6, "whole"),
					NewIngredient("carrot", 6, "whole"),
					NewIngredient("onion", 2, "whole"),
					NewIngredient("beef broth", 4, "cups"),
				},
				[]string{
					"sear roast on all sides",
					"add vegetables and broth",
					"cover and cook at 325F for 3 hours",
				},
				"meat should be fall-apart tender",
			),
			NewRecipe(
				"shepherd's pie",
				[]Ingredient{
					NewIngredient("ground beef", 2, "lbs"),
					NewIngredient("potato", 6, "whole"),
					NewIngredient("carrot", 2, "whole"),
					NewIngredient("peas", 1, "cup"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("butter", 4, "tbsp"),
				},
				[]string{
					"cook and mash potatoes",
					"brown beef with vegetables",
					"spread meat in baking dish",
					"top with mashed potatoes",
					"bake at 375F for 30 minutes",
				},
				"broil top for golden crust",
			),
			// Dinner - Pork
			NewRecipe(
				"pork chops",
				[]Ingredient{
					NewIngredient("pork chops", 4, "whole"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("thyme", 2, "tsp"),
					NewIngredient("butter", 4, "tbsp"),
				},
				[]string{
					"season pork chops",
					"sear in hot pan",
					"add butter, garlic, thyme",
					"bake at 375F for 15 minutes",
				},
				"dont overcook or they dry out",
			),
			NewRecipe(
				"pulled pork",
				[]Ingredient{
					NewIngredient("pork shoulder", 5, "lbs"),
					NewIngredient("BBQ sauce", 2, "cups"),
					NewIngredient("brown sugar", 4, "tbsp"),
					NewIngredient("paprika", 2, "tbsp"),
					NewIngredient("garlic powder", 1, "tbsp"),
				},
				[]string{
					"rub pork with spices",
					"slow cook 8 hours",
					"shred with forks",
					"mix with BBQ sauce",
				},
				"serve on buns with coleslaw",
			),
			NewRecipe(
				"pork fried rice",
				[]Ingredient{
					NewIngredient("pork", 1, "lb"),
					NewIngredient("rice", 4, "cups"),
					NewIngredient("egg", 3, "whole"),
					NewIngredient("soy sauce", 4, "tbsp"),
					NewIngredient("peas", 1, "cup"),
					NewIngredient("carrot", 2, "whole"),
				},
				[]string{
					"cook rice and let cool",
					"dice and cook pork",
					"scramble eggs",
					"fry rice with vegetables",
					"add pork, eggs, soy sauce",
				},
				"day-old rice works best",
			),
			NewRecipe(
				"pork tenderloin",
				[]Ingredient{
					NewIngredient("pork tenderloin", 2, "lbs"),
					NewIngredient("garlic", 6, "cloves"),
					NewIngredient("rosemary", 3, "sprigs"),
					NewIngredient("olive oil", 3, "tbsp"),
				},
				[]string{
					"season tenderloin",
					"sear all sides",
					"roast at 400F for 25 minutes",
					"let rest before slicing",
				},
				"internal temp should be 145F",
			),
			NewRecipe(
				"BBQ ribs",
				[]Ingredient{
					NewIngredient("pork ribs", 3, "racks"),
					NewIngredient("BBQ sauce", 3, "cups"),
					NewIngredient("brown sugar", 1, "cup"),
					NewIngredient("paprika", 3, "tbsp"),
					NewIngredient("garlic powder", 2, "tbsp"),
				},
				[]string{
					"remove membrane from ribs",
					"rub with spices",
					"wrap and bake at 300F for 2 hours",
					"unwrap, brush with sauce",
					"bake 30 more minutes",
				},
				"finish on grill for char",
			),
			NewRecipe(
				"pork schnitzel",
				[]Ingredient{
					NewIngredient("pork cutlets", 4, "whole"),
					NewIngredient("breadcrumbs", 2, "cups"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("flour", 1, "cup"),
					NewIngredient("lemon", 2, "whole"),
				},
				[]string{
					"pound cutlets thin",
					"dredge in flour, egg, breadcrumbs",
					"fry until golden",
					"serve with lemon",
				},
				"keep oil hot for crispy coating",
			),
			// Seafood
			NewRecipe(
				"salmon teriyaki",
				[]Ingredient{
					NewIngredient("salmon", 4, "fillets"),
					NewIngredient("soy sauce", 1, "cup"),
					NewIngredient("brown sugar", 4, "tbsp"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("ginger", 2, "tbsp"),
				},
				[]string{
					"make teriyaki sauce",
					"marinate salmon 20 minutes",
					"bake at 400F for 15 minutes",
					"brush with more sauce",
				},
				"dont overcook salmon",
			),
			NewRecipe(
				"fish tacos",
				[]Ingredient{
					NewIngredient("white fish", 2, "lbs"),
					NewIngredient("tortillas", 12, "whole"),
					NewIngredient("cabbage", 2, "cups"),
					NewIngredient("lime", 3, "whole"),
					NewIngredient("cilantro", 1, "cup"),
				},
				[]string{
					"season and cook fish",
					"warm tortillas",
					"flake fish into pieces",
					"top with cabbage and cilantro",
					"squeeze lime over",
				},
				"add chipotle mayo",
			),
			NewRecipe(
				"shrimp scampi",
				[]Ingredient{
					NewIngredient("shrimp", 2, "lbs"),
					NewIngredient("butter", 8, "tbsp"),
					NewIngredient("garlic", 8, "cloves"),
					NewIngredient("lemon", 2, "whole"),
					NewIngredient("white wine", 1, "cup"),
					NewIngredient("parsley", 1, "cup"),
				},
				[]string{
					"saute garlic in butter",
					"add shrimp and cook",
					"add wine and lemon juice",
					"toss with parsley",
				},
				"serve over pasta or with bread",
			),
			NewRecipe(
				"crab cakes",
				[]Ingredient{
					NewIngredient("crab meat", 1, "lb"),
					NewIngredient("breadcrumbs", 1, "cup"),
					NewIngredient("egg", 1, "whole"),
					NewIngredient("mayo", 4, "tbsp"),
					NewIngredient("old bay seasoning", 2, "tsp"),
				},
				[]string{
					"mix all ingredients gently",
					"form into patties",
					"refrigerate 30 minutes",
					"pan fry until golden",
				},
				"serve with lemon and tartar sauce",
			),
			NewRecipe(
				"baked cod",
				[]Ingredient{
					NewIngredient("cod", 4, "fillets"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("lemon", 2, "whole"),
					NewIngredient("garlic", 4, "cloves"),
					NewIngredient("paprika", 1, "tsp"),
				},
				[]string{
					"place cod in baking dish",
					"top with butter, lemon, garlic",
					"season with paprika",
					"bake at 400F for 15 minutes",
				},
				"fish should flake easily when done",
			),
			NewRecipe(
				"tuna casserole",
				[]Ingredient{
					NewIngredient("tuna", 3, "cans"),
					NewIngredient("egg noodles", 1, "lb"),
					NewIngredient("cream of mushroom soup", 2, "cans"),
					NewIngredient("peas", 2, "cups"),
					NewIngredient("cheese", 2, "cups"),
				},
				[]string{
					"cook noodles",
					"mix with tuna, soup, peas",
					"transfer to casserole dish",
					"top with cheese",
					"bake at 350F for 30 minutes",
				},
				"add potato chips on top for crunch",
			),
			// Sides
			NewRecipe(
				"mashed potatoes",
				[]Ingredient{
					NewIngredient("potato", 6, "whole"),
					NewIngredient("butter", 8, "tbsp"),
					NewIngredient("milk", 1, "cup"),
					NewIngredient("salt", 1, "tsp"),
				},
				[]string{
					"boil potatoes until tender",
					"drain and mash",
					"add butter and milk",
					"whip until fluffy",
				},
				"use russet potatoes for best texture",
			),
			NewRecipe(
				"french fries",
				[]Ingredient{
					NewIngredient("potato", 6, "whole"),
					NewIngredient("oil", 2, "cups"),
					NewIngredient("salt", 1, "tbsp"),
				},
				[]string{
					"cut potatoes into strips",
					"soak in cold water 30 minutes",
					"dry thoroughly",
					"fry at 350F until golden",
					"season with salt",
				},
				"double fry for extra crispy",
			),
			NewRecipe(
				"roasted vegetables",
				[]Ingredient{
					NewIngredient("carrot", 4, "whole"),
					NewIngredient("broccoli", 2, "cups"),
					NewIngredient("bell pepper", 2, "whole"),
					NewIngredient("zucchini", 2, "whole"),
					NewIngredient("olive oil", 4, "tbsp"),
				},
				[]string{
					"chop vegetables",
					"toss with olive oil and seasonings",
					"spread on baking sheet",
					"roast at 425F for 25 minutes",
				},
				"stir halfway through",
			),
			NewRecipe(
				"caesar salad",
				[]Ingredient{
					NewIngredient("romaine lettuce", 2, "heads"),
					NewIngredient("parmesan", 1, "cup"),
					NewIngredient("croutons", 2, "cups"),
					NewIngredient("caesar dressing", 1, "cup"),
				},
				[]string{
					"chop lettuce",
					"toss with dressing",
					"top with parmesan and croutons",
				},
				"add grilled chicken for main dish",
			),
			NewRecipe(
				"coleslaw",
				[]Ingredient{
					NewIngredient("cabbage", 1, "head"),
					NewIngredient("carrot", 2, "whole"),
					NewIngredient("mayo", 1, "cup"),
					NewIngredient("vinegar", 2, "tbsp"),
					NewIngredient("sugar", 2, "tbsp"),
				},
				[]string{
					"shred cabbage and carrots",
					"mix mayo, vinegar, sugar",
					"toss vegetables with dressing",
					"refrigerate 1 hour",
				},
				"better when made ahead",
			),
			NewRecipe(
				"garlic bread",
				[]Ingredient{
					NewIngredient("french bread", 1, "loaf"),
					NewIngredient("butter", 8, "tbsp"),
					NewIngredient("garlic", 6, "cloves"),
					NewIngredient("parsley", 4, "tbsp"),
				},
				[]string{
					"slice bread",
					"mix butter, garlic, parsley",
					"spread on bread",
					"bake at 375F for 10 minutes",
				},
				"broil for extra crispy top",
			),
			NewRecipe(
				"baked beans",
				[]Ingredient{
					NewIngredient("navy beans", 2, "cans"),
					NewIngredient("bacon", 6, "strips"),
					NewIngredient("brown sugar", 1, "cup"),
					NewIngredient("molasses", 4, "tbsp"),
					NewIngredient("onion", 1, "whole"),
				},
				[]string{
					"cook bacon and dice",
					"mix beans with sugar, molasses",
					"add bacon and onion",
					"bake at 350F for 45 minutes",
				},
				"great for BBQ",
			),
			NewRecipe(
				"corn on the cob",
				[]Ingredient{
					NewIngredient("corn", 6, "ears"),
					NewIngredient("butter", 6, "tbsp"),
					NewIngredient("salt", 1, "tsp"),
				},
				[]string{
					"boil water",
					"add corn and cook 5 minutes",
					"serve with butter and salt",
				},
				"grill for smoky flavor",
			),
			NewRecipe(
				"stuffing",
				[]Ingredient{
					NewIngredient("bread", 10, "cups"),
					NewIngredient("celery", 4, "stalks"),
					NewIngredient("onion", 2, "whole"),
					NewIngredient("butter", 8, "tbsp"),
					NewIngredient("chicken broth", 3, "cups"),
				},
				[]string{
					"cube and toast bread",
					"saute celery and onion in butter",
					"mix with bread and broth",
					"bake at 350F for 30 minutes",
				},
				"add sausage for more flavor",
			),
			NewRecipe(
				"rice pilaf",
				[]Ingredient{
					NewIngredient("rice", 2, "cups"),
					NewIngredient("chicken broth", 4, "cups"),
					NewIngredient("onion", 1, "whole"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("parsley", 2, "tbsp"),
				},
				[]string{
					"saute onion in butter",
					"add rice and toast",
					"add broth and simmer",
					"fluff with fork",
				},
				"let sit covered 5 minutes after cooking",
			),
			// Desserts - Cookies
			NewRecipe(
				"chocolate chip cookies",
				[]Ingredient{
					NewIngredient("butter", 1, "cup"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("brown sugar", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("flour", 2, "cups"),
					NewIngredient("chocolate chips", 2, "cups"),
				},
				[]string{
					"cream butter and sugars",
					"beat in eggs",
					"mix in flour",
					"fold in chocolate chips",
					"bake at 375F for 10 minutes",
				},
				"slightly underbake for chewy cookies",
			),
			NewRecipe(
				"sugar cookies",
				[]Ingredient{
					NewIngredient("butter", 1, "cup"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("flour", 3, "cups"),
					NewIngredient("baking powder", 2, "tsp"),
				},
				[]string{
					"cream butter and sugar",
					"add eggs",
					"mix in dry ingredients",
					"roll out and cut shapes",
					"bake at 350F for 8 minutes",
				},
				"decorate with frosting",
			),
			NewRecipe(
				"oatmeal cookies",
				[]Ingredient{
					NewIngredient("butter", 1, "cup"),
					NewIngredient("brown sugar", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("oats", 3, "cups"),
					NewIngredient("flour", 1, "cup"),
					NewIngredient("raisins", 1, "cup"),
				},
				[]string{
					"cream butter and sugar",
					"add eggs",
					"mix in oats, flour, raisins",
					"drop onto baking sheet",
					"bake at 350F for 12 minutes",
				},
				"substitute chocolate chips for raisins",
			),
			NewRecipe(
				"peanut butter cookies",
				[]Ingredient{
					NewIngredient("peanut butter", 1, "cup"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("egg", 1, "whole"),
				},
				[]string{
					"mix all ingredients",
					"roll into balls",
					"press with fork",
					"bake at 350F for 10 minutes",
				},
				"only 3 ingredients needed",
			),
			NewRecipe(
				"gingerbread cookies",
				[]Ingredient{
					NewIngredient("butter", 1, "cup"),
					NewIngredient("brown sugar", 1, "cup"),
					NewIngredient("molasses", 1, "cup"),
					NewIngredient("flour", 4, "cups"),
					NewIngredient("ginger", 2, "tbsp"),
					NewIngredient("cinnamon", 1, "tbsp"),
				},
				[]string{
					"cream butter and sugar",
					"add molasses",
					"mix in dry ingredients",
					"chill dough 2 hours",
					"roll and cut shapes",
					"bake at 350F for 10 minutes",
				},
				"decorate with icing",
			),
			NewRecipe(
				"snickerdoodles",
				[]Ingredient{
					NewIngredient("butter", 1, "cup"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("flour", 3, "cups"),
					NewIngredient("cinnamon", 2, "tbsp"),
				},
				[]string{
					"cream butter and sugar",
					"add eggs",
					"mix in flour",
					"roll in cinnamon sugar",
					"bake at 375F for 10 minutes",
				},
				"dont overbake",
			),
			// Desserts - Cakes
			NewRecipe(
				"chocolate cake",
				[]Ingredient{
					NewIngredient("flour", 2, "cups"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("cocoa powder", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("butter", 1, "cup"),
					NewIngredient("buttermilk", 1, "cup"),
				},
				[]string{
					"mix dry ingredients",
					"beat in wet ingredients",
					"pour into greased pans",
					"bake at 350F for 30 minutes",
					"cool and frost",
				},
				"use coffee to intensify chocolate",
			),
			NewRecipe(
				"vanilla cake",
				[]Ingredient{
					NewIngredient("flour", 3, "cups"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("butter", 1, "cup"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("milk", 1, "cup"),
					NewIngredient("vanilla", 2, "tsp"),
				},
				[]string{
					"cream butter and sugar",
					"add eggs one at a time",
					"alternate flour and milk",
					"add vanilla",
					"bake at 350F for 35 minutes",
				},
				"frost with buttercream",
			),
			NewRecipe(
				"carrot cake",
				[]Ingredient{
					NewIngredient("flour", 2, "cups"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("carrot", 3, "cups"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("oil", 1, "cup"),
					NewIngredient("cinnamon", 2, "tsp"),
				},
				[]string{
					"grate carrots",
					"mix dry ingredients",
					"beat eggs with oil and sugar",
					"fold in carrots and dry mix",
					"bake at 350F for 40 minutes",
				},
				"frost with cream cheese frosting",
			),
			NewRecipe(
				"red velvet cake",
				[]Ingredient{
					NewIngredient("flour", 3, "cups"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("buttermilk", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("cocoa powder", 2, "tbsp"),
					NewIngredient("red food coloring", 2, "tbsp"),
				},
				[]string{
					"mix dry ingredients",
					"beat wet ingredients",
					"add food coloring",
					"combine and bake at 350F for 30 minutes",
				},
				"frost with cream cheese frosting",
			),
			NewRecipe(
				"lemon cake",
				[]Ingredient{
					NewIngredient("flour", 2, "cups"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("butter", 1, "cup"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("lemon", 4, "whole"),
				},
				[]string{
					"cream butter and sugar",
					"add eggs and lemon zest",
					"mix in flour",
					"add lemon juice",
					"bake at 350F for 35 minutes",
				},
				"glaze with lemon icing",
			),
			NewRecipe(
				"cheesecake",
				[]Ingredient{
					NewIngredient("cream cheese", 4, "packages"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("vanilla", 1, "tsp"),
					NewIngredient("graham crackers", 2, "cups"),
					NewIngredient("butter", 8, "tbsp"),
				},
				[]string{
					"mix graham crackers with butter for crust",
					"beat cream cheese and sugar",
					"add eggs one at a time",
					"pour over crust",
					"bake at 325F for 55 minutes",
					"chill overnight",
				},
				"water bath prevents cracks",
			),
			// Desserts - Pies
			NewRecipe(
				"apple pie",
				[]Ingredient{
					NewIngredient("apple", 8, "whole"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("flour", 3, "cups"),
					NewIngredient("butter", 1, "cup"),
					NewIngredient("cinnamon", 2, "tsp"),
				},
				[]string{
					"make pie crust",
					"slice apples",
					"toss with sugar and cinnamon",
					"fill crust with apples",
					"top with crust",
					"bake at 375F for 50 minutes",
				},
				"brush top with egg wash",
			),
			NewRecipe(
				"pumpkin pie",
				[]Ingredient{
					NewIngredient("pumpkin puree", 2, "cups"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("egg", 3, "whole"),
					NewIngredient("heavy cream", 1, "cup"),
					NewIngredient("cinnamon", 1, "tsp"),
					NewIngredient("pie crust", 1, "whole"),
				},
				[]string{
					"mix pumpkin, sugar, spices",
					"beat in eggs and cream",
					"pour into pie crust",
					"bake at 425F for 15 min",
					"reduce to 350F for 40 min",
				},
				"cool completely before serving",
			),
			NewRecipe(
				"pecan pie",
				[]Ingredient{
					NewIngredient("pecans", 2, "cups"),
					NewIngredient("corn syrup", 1, "cup"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("egg", 3, "whole"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("pie crust", 1, "whole"),
				},
				[]string{
					"beat eggs",
					"mix in sugar, syrup, butter",
					"add pecans",
					"pour into pie crust",
					"bake at 350F for 50 minutes",
				},
				"serve with whipped cream",
			),
			NewRecipe(
				"cherry pie",
				[]Ingredient{
					NewIngredient("cherries", 6, "cups"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("cornstarch", 4, "tbsp"),
					NewIngredient("pie crust", 2, "whole"),
				},
				[]string{
					"mix cherries with sugar and cornstarch",
					"pour into bottom crust",
					"top with second crust",
					"cut vents in top",
					"bake at 375F for 45 minutes",
				},
				"can use frozen cherries",
			),
			NewRecipe(
				"key lime pie",
				[]Ingredient{
					NewIngredient("lime", 8, "whole"),
					NewIngredient("sweetened condensed milk", 2, "cans"),
					NewIngredient("egg yolk", 4, "whole"),
					NewIngredient("graham cracker crust", 1, "whole"),
				},
				[]string{
					"juice limes",
					"mix lime juice with condensed milk",
					"beat in egg yolks",
					"pour into crust",
					"bake at 350F for 15 minutes",
					"chill 4 hours",
				},
				"top with whipped cream",
			),
			NewRecipe(
				"lemon meringue pie",
				[]Ingredient{
					NewIngredient("lemon", 6, "whole"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("cornstarch", 6, "tbsp"),
					NewIngredient("egg", 6, "whole"),
					NewIngredient("pie crust", 1, "whole"),
				},
				[]string{
					"make lemon filling with juice and yolks",
					"pour into baked crust",
					"beat egg whites with sugar",
					"spread meringue over filling",
					"bake at 350F for 15 minutes",
				},
				"seal meringue to edges",
			),
			// Desserts - Other
			NewRecipe(
				"brownies",
				[]Ingredient{
					NewIngredient("butter", 1, "cup"),
					NewIngredient("sugar", 2, "cups"),
					NewIngredient("cocoa powder", 1, "cup"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("flour", 1, "cup"),
				},
				[]string{
					"melt butter with sugar",
					"stir in cocoa",
					"beat in eggs",
					"fold in flour",
					"bake at 350F for 25 minutes",
				},
				"dont overbake for fudgy texture",
			),
			NewRecipe(
				"banana bread",
				[]Ingredient{
					NewIngredient("banana", 4, "whole"),
					NewIngredient("butter", 1, "cup"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("flour", 2, "cups"),
					NewIngredient("baking soda", 1, "tsp"),
				},
				[]string{
					"mash bananas",
					"mix with melted butter",
					"stir in sugar and eggs",
					"mix in flour and baking soda",
					"bake at 350F for 60 minutes",
				},
				"use very ripe bananas",
			),
			NewRecipe(
				"rice pudding",
				[]Ingredient{
					NewIngredient("rice", 1, "cup"),
					NewIngredient("milk", 4, "cups"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("egg", 2, "whole"),
					NewIngredient("vanilla", 1, "tsp"),
					NewIngredient("cinnamon", 1, "tsp"),
				},
				[]string{
					"cook rice in milk",
					"stir in sugar",
					"temper eggs and add",
					"cook until thick",
					"add vanilla and cinnamon",
				},
				"serve warm or cold",
			),
			NewRecipe(
				"tiramisu",
				[]Ingredient{
					NewIngredient("ladyfinger cookies", 24, "whole"),
					NewIngredient("mascarpone", 2, "cups"),
					NewIngredient("egg", 6, "whole"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("espresso", 2, "cups"),
					NewIngredient("cocoa powder", 4, "tbsp"),
				},
				[]string{
					"beat egg yolks with sugar",
					"fold in mascarpone",
					"dip cookies in espresso",
					"layer cookies and cream",
					"dust with cocoa",
					"chill 4 hours",
				},
				"use strong coffee",
			),
			NewRecipe(
				"fudge",
				[]Ingredient{
					NewIngredient("chocolate chips", 3, "cups"),
					NewIngredient("sweetened condensed milk", 1, "can"),
					NewIngredient("butter", 4, "tbsp"),
					NewIngredient("vanilla", 1, "tsp"),
				},
				[]string{
					"melt chocolate with milk and butter",
					"stir in vanilla",
					"pour into pan",
					"chill until firm",
					"cut into squares",
				},
				"add nuts if desired",
			),
			NewRecipe(
				"panna cotta",
				[]Ingredient{
					NewIngredient("heavy cream", 4, "cups"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("gelatin", 2, "packets"),
					NewIngredient("vanilla", 2, "tsp"),
				},
				[]string{
					"heat cream and sugar",
					"dissolve gelatin",
					"add vanilla",
					"pour into molds",
					"chill 4 hours",
				},
				"serve with berry sauce",
			),
			NewRecipe(
				"bread pudding",
				[]Ingredient{
					NewIngredient("bread", 8, "cups"),
					NewIngredient("milk", 4, "cups"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("vanilla", 2, "tsp"),
					NewIngredient("cinnamon", 1, "tsp"),
				},
				[]string{
					"cube bread",
					"whisk milk, eggs, sugar, vanilla",
					"pour over bread",
					"let soak 30 minutes",
					"bake at 350F for 45 minutes",
				},
				"serve with caramel sauce",
			),
			NewRecipe(
				"chocolate mousse",
				[]Ingredient{
					NewIngredient("dark chocolate", 8, "oz"),
					NewIngredient("heavy cream", 2, "cups"),
					NewIngredient("egg", 4, "whole"),
					NewIngredient("sugar", 4, "tbsp"),
				},
				[]string{
					"melt chocolate",
					"separate eggs",
					"whip cream",
					"fold everything together",
					"chill 2 hours",
				},
				"use high quality chocolate",
			),
			NewRecipe(
				"creme brulee",
				[]Ingredient{
					NewIngredient("heavy cream", 4, "cups"),
					NewIngredient("egg yolk", 8, "whole"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("vanilla", 2, "tsp"),
				},
				[]string{
					"heat cream with vanilla",
					"whisk yolks with sugar",
					"temper yolks with cream",
					"pour into ramekins",
					"bake in water bath at 325F for 40 minutes",
					"chill then torch sugar on top",
				},
				"need kitchen torch for topping",
			),
			NewRecipe(
				"ice cream",
				[]Ingredient{
					NewIngredient("heavy cream", 2, "cups"),
					NewIngredient("milk", 1, "cup"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("vanilla", 2, "tsp"),
				},
				[]string{
					"heat milk and sugar until dissolved",
					"stir in cream and vanilla",
					"chill completely",
					"churn in ice cream maker",
					"freeze until firm",
				},
				"add mix-ins after churning",
			),
			// Beverages
			NewRecipe(
				"lemonade",
				[]Ingredient{
					NewIngredient("lemon", 8, "whole"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("water", 6, "cups"),
				},
				[]string{
					"juice lemons",
					"dissolve sugar in hot water",
					"mix with lemon juice and cold water",
					"serve over ice",
				},
				"adjust sweetness to taste",
			),
			NewRecipe(
				"iced tea",
				[]Ingredient{
					NewIngredient("tea bags", 6, "whole"),
					NewIngredient("water", 8, "cups"),
					NewIngredient("sugar", 1, "cup"),
					NewIngredient("lemon", 2, "whole"),
				},
				[]string{
					"boil water",
					"steep tea bags 5 minutes",
					"remove bags and add sugar",
					"cool and serve over ice",
					"garnish with lemon",
				},
				"use black tea",
			),
			NewRecipe(
				"hot chocolate",
				[]Ingredient{
					NewIngredient("milk", 4, "cups"),
					NewIngredient("cocoa powder", 4, "tbsp"),
					NewIngredient("sugar", 4, "tbsp"),
					NewIngredient("vanilla", 1, "tsp"),
				},
				[]string{
					"heat milk",
					"whisk in cocoa and sugar",
					"add vanilla",
					"top with whipped cream",
				},
				"add marshmallows",
			),
			NewRecipe(
				"margarita",
				[]Ingredient{
					NewIngredient("tequila", 4, "oz"),
					NewIngredient("lime juice", 2, "oz"),
					NewIngredient("triple sec", 2, "oz"),
					NewIngredient("ice", 2, "cups"),
					NewIngredient("salt", 1, "tbsp"),
				},
				[]string{
					"rim glass with salt",
					"blend tequila, lime, triple sec with ice",
					"pour into glass",
				},
				"can also serve on rocks",
			),
			NewRecipe(
				"mojito",
				[]Ingredient{
					NewIngredient("rum", 4, "oz"),
					NewIngredient("lime", 2, "whole"),
					NewIngredient("mint", 20, "leaves"),
					NewIngredient("sugar", 4, "tbsp"),
					NewIngredient("club soda", 2, "cups"),
				},
				[]string{
					"muddle mint and sugar",
					"add lime juice",
					"add rum and ice",
					"top with club soda",
				},
				"garnish with mint sprig",
			),
		},
	}
}
